feat: Add interface so ollama client can do embedding
bosun-ai/swiftide pull request #278
Opened 2024-09-07 21:28 UTC by ephraimkunz

Update to the most recent ollama-rs, which exposes the batch embedding API Ollama exposes (https://github.com/pepperoni21/ollama-rs/pull/61). This allows the Ollama struct in Swiftide to implement `EmbeddingModel`. 

Use the same pattern that the OpenAI struct uses to manage separate embedding and prompt models.

2024-09-07 21:29 UTC, ephraimkunz commented on swiftide-integrations/src/ollama/mod.rs
> +    }
Ensure that setting both prompts don't overwrite or delete the other.

2024-09-07 21:31 UTC, ephraimkunz commented
I'm going to create a separate PR to update the documentation on the website. I'll link to it here when it's out for review.

2024-09-07 21:56 UTC, ephraimkunz commented
Updated the website in https://github.com/bosun-ai/swiftide-website/pull/15

2024-09-08 14:44 UTC, timonv commented
Awesome, looking good, I'll do a full review asap

2024-09-08 14:53 UTC, tinco submitted a review, later dismissed
I checked this over and it looks great! :)

2024-09-08 19:43 UTC, timonv requested changes
Looks great, thanks for this! Small comment on naming.

2024-09-08 19:43 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +            openai.default_options.prompt_model,
Could you fix the naming here? Should be ollama, not openai.

2024-09-08 19:47 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +            openai.default_options.prompt_model,
```suggestion
            ollama.default_options.prompt_model,
```

2024-09-08 19:47 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +        let openai = Ollama::builder()
```suggestion
        let ollama = Ollama::builder()
```

2024-09-08 19:47 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +            openai.default_options.embed_model,
```suggestion
            ollama.default_options.embed_model,
```

2024-09-08 19:48 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +        let openai = Ollama::builder()
```suggestion
        let ollama = Ollama::builder()
```

2024-09-08 19:48 UTC, timonv commented on swiftide-integrations/src/ollama/mod.rs
> +            openai.default_options.embed_model,
```suggestion
            ollama.default_options.embed_model,
```

2024-09-08 19:50 UTC, timonv approved these changes
Renamed it. Great work! Will be merging and releasing this in a bit! 🙏

2024-09-08 20:05 UTC, merged