feat(query): Add custom lancedb query generation for lancedb search
bosun-ai/swiftide pull request #518
Opened 2024-12-31 14:04 UTC by shamb0

Fixes: #511

2025-01-01 15:35 UTC, timonv requested changes
Nice! Couple of comments

2025-01-01 15:35 UTC, timonv commented on swiftide/tests/lancedb.rs
> +        .expect("Failed to open vector search table 'swiftide_test'");
I wonder if this would keep the connection open, and force a single connection to be used for the full query pipeline. That might be an unintentional bottleneck.

2025-01-01 15:35 UTC, timonv commented on swiftide/tests/lancedb.rs
> +            move |query_node| -> Result<lance_query_builder::VectorQuery> {
If that's the case, maybe (thinking very meta), it's possible to yield the strategy here too. And then having the concrete implementation of the strategy (so specific for lance), yield an active table connection.

Honestly, it sounds rather complicated, I don't have an off the bat solution

2025-01-01 15:35 UTC, timonv commented on swiftide-integrations/src/lancedb/retrieve.rs
> +impl Retrieve<CustomStrategy<query::VectorQuery>> for LanceDB {
Lancedb has a (not judging) bit confusing setup with concrete types starting at Query, which can be converted to a VectorQuery, they implement QueryBase and ExecutableQuery. I think ExecutableQuery is probably the type you want, but it's not dyn compatible (might still work with generics). Then a single implementation would work for both query types.

2025-01-01 15:35 UTC, timonv commented on swiftide-integrations/src/lancedb/retrieve.rs
> +                }
Perhaps nice to refactor this to a `from_record_batch(batch) -> Documents`, so the code isn't duplicated across retriever implementations

2025-01-01 15:35 UTC, timonv commented on swiftide/tests/lancedb.rs
> +                let result_limit = usize::try_from(similarity_config.top_k())
Maybe just use an arbitrary number? Feels a bit complicated to just create a new search strategy, if you really need a number.

2025-01-09 11:50 UTC, shamb0 commented
Hi @timonv,

I've updated the custom strategy implementation in `swiftide-core/src/search_strategies/custom_strategy.rs` to handle async query builders, addressing your feedback about LanceDB connection management. The documentation has been streamlined as well.

    https://github.com/bosun-ai/swiftide/pull/518#discussion_r1900417336
    https://github.com/bosun-ai/swiftide/pull/518#discussion_r1900417831

Would appreciate your thoughts on whether this prototype aligns with your expectations.

2025-01-12 15:35 UTC, timonv approved these changes
Nice work, this is really good! Will merge it asap.

2025-01-16 13:43 UTC, merged